language: ruby

rvm:
  - 2.3.3

addons:
  postgresql: 9.6

postgres:
  adapter: postgresql
  database: api_test
  username: api

before_script:
  - psql -c 'create database social_network_test;' -U postgres
  - cd api/

script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rake db:test:prepare
